# Theme Settings
# https://mmistakes.github.io/minimal-mistakes/docs/configuration/

### Site settings
locale: 'en-US'
timezone: America/New_York
theme: 'minimal-mistakes-jekyll'
minimal_mistakes_skin: 'dark'

### Metadata
title: 'Hawk Eye The Rapper'
title_separator: ': '
subtitle: '#Reincarnated2Resist'
name: 'Hawk Eye The Rapper'
description: 'Open Source Interface'
url: 'TO BE SET FROM MAKEFILE'
baseurl: 'TO BE SET FROM MAKEFILE'
repository: https://github.com/HawkEyeTheRapper/HawkEyePages
teaser: /assets/images/logos/logo.png
logo: /assets/images/logos/logo.png
masthead_title: 'Hawk Eye Is Back!'

### Header
head_scripts:
    - /assets/js/tabs.js
    - /assets/js/quiz.js
    - /assets/js/accordion.js
    - https://code.jquery.com/jquery-3.2.1.min.js

### Navigation
breadcrumbs: true
breadcrumb_home_label: 'Home'
breadcrumb_separator: '>'
words_per_minute: 200
search: true
search_full_content: true
search_provider: lunr

### Site Author
author:
    name: 'Hawk Eye'
    avatar: '/assets/images/logos/logo_square.png'
    bio: 'Be a **hero**.'
    location: 'US'
    links:
        - label: 'Website'
          icon: 'fas fa-fw fa-link'
          url: 'https://www.HawkEyeTheRapper.com'

### Site Footer
footer:
    links:
        - label: 'Website'
          icon: 'fas fa-fw fa-link'
          url: 'https://www.HawkEyeTheRapper.com'
      

atom_feed:
    hide: true

### Markdown Processing
markdown_ext: 'markdown,mkdown,mkdn,mkd,md'
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false
kramdown:
    input: GFM
    hard_wrap: false
    auto_ids: true
    footnote_nr: 1
    entity_output: as_char
    toc_levels: 1..6
    smart_quotes: lsquo,rsquo,ldquo,rdquo
    enable_coderay: false

# Reading Files
include:
    - .htaccess
    - _pages
exclude:
    - '*.sublime-project'
    - '*.sublime-workspace'
    - .vscode
    - vendor
    - .asset-cache
    - .bundle
    - .jekyll-assets-cache
    - .sass-cache
    - CHANGELOG
    - Gemfile
    - LICENSE
    - log
    - node_modules
    - package.json
    - package-lock.json
    - python_sdk/
    - _demos/python/tutorial
    - README.md
keep_files:
    - .git
    - python_sdk

### Sass/SCSS
sass:
    sass_dir: _sass
    style: compressed # https://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style

### Plugins
plugins:
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-gist
    - jekyll-include-cache
    - jekyll-default-layout
    - jekyll-optional-front-matter
    - jekyll-titles-from-headings
    - jekyll-relative-links
    - jekyll-spaceship
    - jekyll-redirect-from

titles_from_headings:
    enabled: true
    strip_title: true
    collections: true

# HTML Compression
# - https://jch.penibelst.de/
compress_html:
    clippings: all
    ignore:
        envs: development

# Collections
collections_dir: tutorials
collections:
    python-tutorials:
        output: true
        collections_dir: python-tutorials
        sort_by: lesson
    bash-tutorials:
        output: true
        collections_dir: bash-tutorials
        sort_by: lesson
    demos:
        output: true
        collection_dir: demos

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true


jekyll-spaceship:
    # default enabled processors
    processors:
        - table-processor
        - mathjax-processor
        - plantuml-processor
        - mermaid-processor
        - polyfill-processor
        - media-processor
        - emoji-processor
        - element-processor
    mathjax-processor:
        src:
            - https://polyfill.io/v3/polyfill.min.js?features=es6
            - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
        config:
            tex:
                inlineMath:
                    - ['$', '$']
                    - ['\(', '\)']
                displayMath:
                    - ['$$', '$$']
                    - ['\[', '\]']
            svg:
                fontCache: 'global'
        optimize: # optimization on building stage to check and add mathjax scripts
            enabled: true # value `false` for adding to all pages
            include: [] # include patterns for math expressions checking (regexp)
            exclude: [] # exclude patterns for math expressions checking (regexp)
    plantuml-processor:
        mode: pre-fetch # fetch image at build-time
        css:
            class: plantuml
        syntax:
            code: 'plantuml!'
            custom: ['@startuml', '@enduml']
        src: http://plant_uml:8080/svg/
    mermaid-processor:
        mode: pre-fetch # fetch image at build-time
        css:
            class: mermaid
        syntax:
            code: 'mermaid!'
            custom: ['@startmermaid', '@endmermaid']
        config:
            theme: default
        src: https://mermaid.ink/svg/
    media-processor:
        default:
            id: 'media-{id}'
            class: 'media'
            width: '100%'
            height: 350
            frameborder: 0
            style: 'max-width: 600px; outline: none;'
            allow: 'encrypted-media; picture-in-picture'
    emoji-processor:
        css:
            class: emoji
        src: https://github.githubassets.com/images/icons/emoji/
